apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-blue-tls
  namespace: prod-blue
spec:
  secretName: prod-blue-tls
  dnsNames:
    - dev-ops-project.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
