apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-green-tls
  namespace: prod-green
spec:
  secretName: prod-green-tls
  dnsNames:
    - preprod.dev-ops-project.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
