apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: env-ingress
  namespace: uat
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - uat.dev-ops-project.com
      secretName: uat-tls

  rules:
    - host: uat.dev-ops-project.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blue-service
                port:
                  number: 80

          - path: /red(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: red-service
                port:
                  number: 80

          - path: /blue(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: blue-service
                port:
                  number: 80

          - path: /green(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: green-service
                port:
                  number: 80
