apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-service-prod-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Aniket-ITSUSF/final_devops_infra.git'
    targetRevision: main
    path: 'manifests/k8s/blue-service/prod-green'
  destination:
    name: prod
    namespace: prod-green
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
