apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-service-uat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Aniket-ITSUSF/final_devops_infra.git'
    targetRevision: uat
    path: 'manifests/k8s/blue-service/uat'
  destination:
    name: uat
    namespace: uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
