apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: green-service-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/Aniket-ITSUSF/final_devops_infra.git'
    targetRevision: main
    path: 'manifests/helm-charts/green-service'
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    name: prod
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
