apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/Aniket-ITSUSF/final_devops_infra.git'
    targetRevision: main
    path: 'manifests/k8s/ingress-dev.yaml'

  destination:
    name: dev
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
