apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: red-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Aniket-ITSUSF/final_devops_infra.git'
    targetRevision: main
    path: 'manifests/k8s/red-service/dev'
  destination:
    name: dev
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
