apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: red-service-prod-blue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Aniket-ITSUSF/final_devops_infra.git'
    targetRevision: main
    path: 'manifests/k8s/red-service/prod-blue'
  destination:
    name: prod
    namespace: prod-blue
  syncPolicy: {}
