apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: red-service-uat
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      red-service=654654391642.dkr.ecr.us-east-1.amazonaws.com/red-service
    argocd-image-updater.argoproj.io/red-service.uat.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/Aniket-ITSUSF/final_devops_infra.git
    targetRevision: uat
    path: manifests/k8s/red-service/uat
  destination:
    name: uat
    namespace: uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
